config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :styles
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "breweries#index"
  get "all_beers", to: "beers#index"
  post "beers", to: "beers#create"
  get "ratings", to: "ratings#index"
  get "ratings/new", to:"ratings#new"
  post "ratings", to: "ratings#create"
  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  delete "signout", to: "sessions#destroy"
  get "memberships", to: "memberships#index"
  get "memberships/new", to: "memberships#new"
  post "memberships", to: "memberships#create"
  post "places", to: "places#search"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navibar">
      <%= link_to "Breweries", breweries_path %>
      <%= link_to "Beers", beers_path %>
      <%= link_to "Ratings", ratings_path %>
      <%= link_to "Clubs", beer_clubs_path %>
      <%= link_to "Places", places_path %>
      <%= link_to "Styles", styles_path %>
      <%= link_to "Users", users_path %>
      <% if current_user %>
        <%= link_to current_user.username, current_user %>
        <%= link_to "New Rating", ratings_new_path %>
        <%= link_to "Join a Club", memberships_new_path %>
        <%= link_to "Sign Out", signout_path, data: { "turbo-method": :delete } %>
      <% else %>
        <%= link_to "Sign In", signin_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>

</html>